language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- wget https://github.com/usc-isi-i2/Web-Karma/releases/download/v2.053/karma-spark-0.0.1-SNAPSHOT-shaded.jar
- mkdir output
- python run_workflow.py
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LXyIlGWwCBoES0XLiWQmf8RoqQ8ETNICSTk/p3ABqCbFnIVre6m2kwjLveCoXgvBrEBM/tU2F8KA/+emiAC4MXy/6652AJ/qTShVEyA51FhLcGh4fGeYVRs209EgYk+lKOarpolaC5PTpS3TCtsa2ZDR1l3h2yQNgT12bdIEM7XpQiJ9cDcC6NLMjLc/HsvyRq4a3TwOSXSIKohqbgltFiUoodIlEU2kcQzlR4A5i7UpMM+puDMK58CdpFAlHAuRk0wgO4f+PxbuouttcGTwnlq/OCZz+JeanhNLRnS27i6Wb1Ren0iTzBa2R4C4adEvFOUvgE79/3iRp/4uWrKEW+aNhwTbYibM6Friv9yH3oIGGBETzcsfOT+LbBAw7LtZtSETgQwT81R084hg6mEyaWz81jYTsMqj0fUwDFbzvf5j5LFfp0t0cvq345lHl0SYa3sKShe135MLf/+vrfhgaWD7Rde9lCoIA27cg/tW8FUFAHmYjnrY4bFWGwQfdqdtEz4Uq2qdrSgpZB6qq/75t806GoEmxCLKPdJyspfAuy0xTKTzm8W231Z8Bosvo/gC7Y9Iy9g600hCaQlJAu86taBWi7H+bMV1jrz6WQMR0L3KfFyjc/tc2kt6tt31yzgGSzAQR2mIKlRnZNOmhiZf38qbFvQtuxR7kZNKjViR1y0=
  file: output/test.rdf
  on:
    tags: true
